[project]
name = "SouthsideMusic"
version = "v42"
description = "Advanced music player"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "darkdetect>=0.8.0",
    "hpyt>=1.4.0",
    "mutagen>=1.47.0",
    "numpy>=2.4.2",
    "pillow>=12.2.0",
    "pydub>=0.25.1",
    "psutil>=7.2.0",
    "pycryptodome>=3.23.0",
    "qrcode>=8.2",
    "requests>=2.32.5",
    "scipy>=1.17.0",
    "sounddevice>=0.5.5",
    "toml>=0.10.2",
    "tornado>=6.5.4",
    "tqdm>=4.67.3",
    "audioop-lts>=0.2.2",
    "openai>=2.43.0",
    "pywin32>=311",
    "anthropic>=0.112.0",
    "markdown-it-py>=3.0.0",
    "ziamath==0.13",
]
